version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: Release
    environment:
      DISCORD_TOKEN: NO_BOT_TOKEN
    container_name: discpp-bot
    volumes:
      - .:/app
